### ISSUE TITLE
disable and enable video

### ISSUE THREAD

**Issue by nimajnsr** [apivideo/api.video-reactnative-live-stream#10]
Adding an option to enable and disable video would be great. 
Similar to the mute option we have on audio, this allows us to broadcast only audio, in that situation, It would be great if you could offer to us to add an image or something alternative to a black/blank video for showing to users while we disable video.

**Comment by zenibandy** [comment]
Thanks for the suggestion! While we do not have any plans on the roadmap to prioritize audio, I have added this idea to the backlog

**Comment by ThibaultBee** [comment]
Thanks again for suggesting a new feature. We are already focus on 100 of api.video projects. We believe this feature is too complex and too specific. We have no plan to implement this feature. -> Closing
