### ISSUE TITLE
npm module is not even installing, any issues there?

### ISSUE THREAD

**Issue by rubensavio** [apivideo/api.video-reactnative-live-stream#14]

**Comment by ThibaultBee** [comment]
Hi,

I just tried to install it with npm, everything was fine.
Do you have an error trace or something?
Is this related to https://github.com/apivideo/api.video-reactnative-live-stream/issues/11 ?

Regards,
Thibault

**Comment by rubensavio** [comment]
Hi @ThibaultBee 

Thanks for the quick reply. I directly added it to my package.json & installed. Works fine, problem was my command tool. 

Now, my query is if I need to only use the broadcaster on react native & send the stream to my own rtmp server, will it work? For some reason when I run with this npm package, I get Internet access failed error. Is there something like an api key I need to add? Thanks

**Comment by ThibaultBee** [comment]
You can use this live stream to your own RTMP server.
There are no API key restriction to download this package. But jcenter, one of java dependencies repository, seems to be unstable at the moment. jcenter is going to close in 2 weeks so I already prepared the migration. I will anticipate a release.

**Comment by rubensavio** [comment]
Ah ok, thanks for the heads up. Does this mean the example project wont run as well? We have installed & tried to run but its not building properly. Sharing the error on my end,

Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/shobhitmandloi/Documents/react-native/api.video-reactnative-live-stream/src/index.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project.

**Comment by ThibaultBee** [comment]
The example should build as well. It is currently working on CI.
Can you clean your project et re-run 'yarn'?

**Comment by rubensavio** [comment]
yes, tried on my end as well. same error. example is building but failing while bundling. 

 BUNDLE  ./index.tsx

error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from C:\Users\Ruben\baaz_app\api.video-reactnative-live-stream-main\src\index.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project.


can you try the example project, if its fine?

**Comment by rubensavio** [comment]
Am using npm install not yarn & then as usual react-native run-android

**Comment by rubensavio** [comment]
And  now sure if you have faced this issue before. I also tried to add this package into my own project. App installs & builds. Now when I open, the projects calls the first api & at that moment I get "Network access failed". If I remove the api.video npm package, api works fine. 

Any comments? would appreciate if you can respond on this.

**Comment by ThibaultBee** [comment]
Did you manage the permissions as in https://github.com/apivideo/api.video-reactnative-live-stream#permissions?
Can you provide a screenshot? Error log?

**Comment by rubensavio** [comment]
Yes, the setup is all done. Unable to share the code, error log I will try to share. Main error that pops is "Network access failed". Am also a little baffled on why an api is failing when I add this package. Could it be coz of the api endpoint being http? Trying to think on every direction at the moment.

That's why I thought of trying the example, but that isnt bundling properly for me to test out.

**Comment by rubensavio** [comment]
Sharing the screenshot of the network fail. Am using fetch method to call post api in this case
![WhatsApp Image 2022-01-22 at 12 07 57 AM](https://user-images.githubusercontent.com/58161472/150582055-66944ac2-5efc-492e-b5c4-a9efb7007358.jpeg)

**Comment by rubensavio** [comment]
@ThibaultBee so the java error, I get is as below

NoSuchMethodError
No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie')

There is some version discrepancy in the okhttp dependency. Let me know if this is something you have com across & can be fixed

**Comment by olivierapivideo** [comment]
Hi @rubensavio 

Indeed it seems that the version of okhttp that you use is not the same as the one embedded in our library.

Unfortunately your problem is a bit beyond the scope of this repository and we don’t have a lot of time to spend on it.

You should be able to fix this problem by setting the version of okhttp to use in your gradle configuration. Searching for something like “react native okhttp version incompatibility » on google you should find some interesting answers.

**Comment by rubensavio** [comment]
Hi @olivierapivideo 

Thanks for responding. In fact I have figured out work around on this. Finally was able to successfully integrate api.video npm package into my project & run. Couple things we noticed,

1. Audio whatever bitrate I try is always distorted
2. While am live, if I get a whatsapp call then the app goes to background. In such scenario, the video stream cuts off making the server disconnect the whole stream. But on facebook live if something like this happens, the video & audio does not go off, it reconnects when you get back. 

Any comment on this?

**Comment by rubensavio** [comment]
@olivierapivideo  @ThibaultBee Any comment on my previous message.

**Comment by olivierapivideo** [comment]
Hi @rubensavio ,

Regarding your audio issue, can you record a sample live on api.video ? (by creating a live using the API with record = true ).

Regarding your second point this will also require some change from our backend side, we've planned to work on that topic during this year.

**Comment by slodhi786** [comment]
@olivierapivideo do we have any update on @rubensavio second point?

**Comment by olivierapivideo** [comment]
Hi @slodhi786 ,
No, we have not made any progress on this point for the moment. 
We will keep you informed when we release this feature.

**Comment by rubensavio** [comment]
@ThibaultBee @slodhi786 @olivierapivideo Hi Guys, any update on the live stream disconnecting while whatsapp or any other incoming call happens?

**Comment by olivierapivideo** [comment]
Hi Ruben,
No progress on this topic for the moment. Unfortunately we won’t be able to tackle that before several months.

**Comment by olivierapivideo** [comment]
Closing since this is still not in our roadmap.
