### ISSUE TITLE
Are any settings variable during stream?

### ISSUE THREAD

**Issue by Psionyx** [apivideo/api.video-reactnative-live-stream#15]
Thanks for the work you've done on this library, The issue I'm having is that when I stream to go live, I lose control over settings and seem unable to change the resolution or bitrate. Sometimes due to connection speed, it may be necessary to reduce the resolution or the bitrate to ensure the stream continues? How would you recommend we workaround this?

**Comment by ThibaultBee** [comment]
Hello,

Changing resolution during a live streaming is not that easy. I am not sure decoder/player supports it.
But we should definitely have a way to set video bitrate on the fly.

We are working on a new version of this package (see https://github.com/apivideo/api.video-reactnative-live-stream/tree/feature/refactor). We will add this as soon as it is stable.

Best regards,
Thibault

**Comment by Psionyx** [comment]
Yep I understand about resolution. In fact I just found out Youtube doesn't allow you to change some of those things mid stream, but video bitrate is definitely variable so if that could be prioritized. Thanks for your work on this!
