### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Holzmichel41** [apivideo/api.video-reactnative-live-stream#20]
**Describe the bug**
The bug occurs as soon as the screen with the `<LiveStreamView />` component is opened a second time (> 1) and the component is re-rendered. The app crashes immediately and an error log is issued with the following error: 
`Fatal error: Unexpectedly found nil while unwrapping an Optional value`.

**To Reproduce**
1. Create a react-native application with more than one screen
2. Put the `<LiveStreamView />` component on the second screen
3. Open the screen more than one time (or probably trigger a rerender in another way)

**Expected behavior**
The app is going to crash with the following error message: `Fatal error: Unexpectedly found nil while unwrapping an Optional value`

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.5
 - Version 1.0.0

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: DDB756FE-59F8-40BB-8D86-FA41FBD58A30
CrashReporter Key:   10736A7A-E9D7-3061-3D4C-DB9C574F2979
Hardware Model:      MacBookPro16,1
Process:             studio [8005]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/381ADF7A-5ED0-4D10-B2AD-D91E3F05E31E/data/Containers/Bundle/Application/A58DF142-0EEB-422D-A4AC-C35D637C2898/studio.app/studio
Identifier:          com.shopshot.studio
Version:             1.0.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [613]
Coalition:           com.apple.CoreSimulator.SimDevice.381ADF7A-5ED0-4D10-B2AD-D91E3F05E31E [709]
Responsible Process: SimulatorTrampoline [542]

Date/Time:           2022-03-28 23:06:27.6416 +0200
Launch Time:         2022-03-28 22:55:58.0951 +0200
OS Version:          macOS 12.2 (21D49)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 4 Illegal instruction: 4
Terminating Process: exc handler [8005]

Triggered by Thread:  0

Application Specific Information:
CoreSimulator 802.6 - Device: iPhone 12 (381ADF7A-5ED0-4D10-B2AD-D91E3F05E31E) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 12
HaishinKit/AVVideoIOUnit.swift:251: Fatal error: Unexpectedly found nil while unwrapping an Optional value
dyld4 config: DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.5.simruntime/Contents/Resources/RuntimeRoot

**Comment by ThibaultBee** [comment]
Hi,

Thank you for reporting this issue.
We are trying to reproduce it right now. It should be fix quickly! :)

Regards

**Comment by ThibaultBee** [comment]
Hi,

You try to reproduce the crash with a 2 screens application but we could not make it crash. See  https://github.com/apivideo/api.video-reactnative-live-stream/tree/bug/multiple_views
Do you have a clue on what we are missing?

Best regards,
Thibault

**Comment by ThibaultBee** [comment]
No news for this issue -> Closing.
Feel free to reopen if you still face a similar isuee.
