### ISSUE TITLE
Support autofocus

### ISSUE THREAD

**Issue by chetankumar01** [apivideo/api.video-reactnative-live-stream#21]
**Is your feature request related to a problem? Please describe.**
Auto focus would improve stream quality a lot. 

**Describe the solution you'd like**
I think Haishinkit has support of continuousFocus, we could expose it as a prop?

**Describe alternatives you've considered**
I am still exploring.

**Comment by ThibaultBee** [comment]
Hi,

So you are saying that it does not automatically focus on the targeted object? The focus is fixed?
If it is missing, we should definitely add that.

Best regards,
Thibault

**Comment by chetankumar01** [comment]
I forked and updated the dependency to use 0.2.0 of `api.video-ios-live-stream` and it seems to be working fine for me. Will do some more tests and update again. Thank you for looking into this.

**Comment by ThibaultBee** [comment]
Hi,

I just check your branch. You might want to get the result of `startStreaming` when it returns an error or an exception on the RN side.
It will be fixed in our next release of `api.video-reactnative-live-stream` (v1.1.0) but we still have some stuff to work on.

Regards,
Thibault
