### ISSUE TITLE
Switch camera and videoResolution not working

### ISSUE THREAD

**Issue by codal-mpawar** [apivideo/api.video-reactnative-live-stream#22]
- Switch camera
- video resolution

Both option is not working. 1.0.0 version @dighan @fancyweb @Titozzz @josebarcelon @herve-api-video

**Comment by ThibaultBee** [comment]
Hi,

To help you, we will need a lot more information like
-  Which phone?
- Are you trying to switch from back to frontcamera or front to back camera (or other)?
- What resolutions?
You know that you can't set a resolution when the library is streaming?

Could you please open a new issue and fill the `Bug report` fields? Thank you.

Regards,
Thibault
