### ISSUE TITLE
Fatal crash when opening screen

### ISSUE THREAD

**Issue by lewatt23** [apivideo/api.video-reactnative-live-stream#25]
**Describe the bug**
When installing the application no matter what i do on my samsung s7 android 8.0 the app crash, at frist i thought i was because of the android version but am just from testing on my redmi note 10 with android 12 same issue different outcome there the issue is that the stream start but doesn't send any package and disconnect  as soon as it started. is worth noting i have tested 2 different backends both written in go and nodejs but the output is still the same, but they both work well with OBS.

**To Reproduce**
1. Clone example repo and install dep.
2. Run react-native
3. App crash on android 8.0 or doesn't send any package on android 12.

**Expected behavior**
The appication is suppose to stream my screen

**Smartphone (please complete the following information):**
 - Device: Redmi  Note 10
 - OS: Android 
 - Version :12 

**Additional context**
Here is the different logs from flipper

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Cannot figure out the cause

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Build fingerprint: 'Redmi/sunny_in/sunny:12/SKQ1.210908.001/V13.0.1.0.SKGINXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-05-23 13:07:47.398812292+0100
Process uptime: 0s
Cmdline: video.api.reactnative.livestream.example
pid: 19554, tid: 19773, name: VMediaCodecThre  >>> video.api.reactnative.livestream.example <<<
uid: 10422
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000072465250  x2  00000000000009b8  x3  0000007e6acc0f5f
    x4  0000007e527f6688  x5  000000000000004a  x6  284901ff3a435328  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  9e24f0d7579eb989  x10 0000000000430000  x11 000000000000001c
    x12 00000000000000ff  x13 0000000000000000  x14 7ffbffff00000000  x15 0000000000000000
    x16 0000007dc985ef10  x17 0000007dcd85a504  x18 0000007d9576e000  x19 b400007e53a58400
    x20 0000000000000000  x21 0000000000000030  x22 0000007debe5fc06  x23 0000000000004070
    x24 0000007e6ae00880  x25 0000007e527f68a8  x26 0000007e527f68bc  x27 0000007e527f68a8
    x28 0000007e527f67a0  x29 0000007e527f6780
    lr  0000007e6aed4048  sp  0000007e527f6730  pc  0000007dcd85a520  pst 0000000060000000
backtrace:
      #00 pc 0000000000014520  /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/lib/arm64/librtmp.so (RTMP_Write+28) (BuildId: bfd03f379ed41c82df8ea932a4ccf15bcfbc66dd)
      #01 pc 00000000002d4044  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #02 pc 000000000020a0a0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #03 pc 000000000017ac06  [anon:dalvik-classes6.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk!classes6.dex]
      #04 pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #05 pc 0000000000467ad2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #06 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #07 pc 00000000004791a8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #08 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #09 pc 000000000046b978  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #10 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #11 pc 0000000000479324  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #12 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #13 pc 00000000004688f6  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #14 pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #15 pc 000000000031f806  /system/framework/framework.jar
      #16 pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #17 pc 000000000031fae0  /system/framework/framework.jar
      #18 pc 000000000200ece0  /memfd:jit-cache (deleted) (android.os.Handler.dispatchMessage+272)
      #19 pc 0000000002038b48  /memfd:jit-cache (deleted) (android.os.Looper.loopOnce+1480)
      #20 pc 0000000002016878  /memfd:jit-cache (deleted) (android.os.Looper.loop+696)
      #21 pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #22 pc 00000000002ee6b8  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+320) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #23 pc 000000000040ade4  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+820) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #24 pc 000000000076d4b8  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+3812) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #25 pc 00000000002c5014  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #26 pc 00000000004490d8  /system/framework/framework.jar
      #27 pc 000000000027d840  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.3351068054637636664)+644) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #28 pc 000000000027c9e8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1176) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #29 pc 00000000002d4178  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #30 pc 00000000002ca764  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #31 pc 000000000030e980  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+156) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #32 pc 00000000003c1db4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+380) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #33 pc 00000000004578ec  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+992) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #34 pc 00000000000f0d34  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: e1f31041be009cf8613d6678cdccd160)
      #35 pc 000000000008d57c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: e1f31041be009cf8613d6678cdccd160)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/sunny_in/sunny:12/SKQ1.210908.001/V13.0.1.0.SKGINXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-05-23 13:07:47.398812292+0100
Process uptime: 0s
Cmdline: video.api.reactnative.livestream.example
pid: 19554, tid: 19773, name: VMediaCodecThre  >>> video.api.reactnative.livestream.example <<<
uid: 10422
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000072465250  x2  00000000000009b8  x3  0000007e6acc0f5f
    x4  0000007e527f6688  x5  000000000000004a  x6  284901ff3a435328  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  9e24f0d7579eb989  x10 0000000000430000  x11 000000000000001c
    x12 00000000000000ff  x13 0000000000000000  x14 7ffbffff00000000  x15 0000000000000000
    x16 0000007dc985ef10  x17 0000007dcd85a504  x18 0000007d9576e000  x19 b400007e53a58400
    x20 0000000000000000  x21 0000000000000030  x22 0000007debe5fc06  x23 0000000000004070
    x24 0000007e6ae00880  x25 0000007e527f68a8  x26 0000007e527f68bc  x27 0000007e527f68a8
    x28 0000007e527f67a0  x29 0000007e527f6780
    lr  0000007e6aed4048  sp  0000007e527f6730  pc  0000007dcd85a520  pst 0000000060000000
backtrace:
      #00 pc 0000000000014520  /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/lib/arm64/librtmp.so (RTMP_Write+28) (BuildId: bfd03f379ed41c82df8ea932a4ccf15bcfbc66dd)
      #01 pc 00000000002d4044  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #02 pc 000000000020a0a0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #03 pc 000000000017ac06  [anon:dalvik-classes6.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk!classes6.dex]
      #04 pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #05 pc 0000000000467ad2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #06 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #07 pc 00000000004791a8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #08 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #09 pc 000000000046b978  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #10 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #11 pc 0000000000479324  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #12 pc 000000000020ae64  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #13 pc 00000000004688f6  [anon:dalvik-classes.dex extracted in memory from /data/app/~~_QAk2eMv1ChyjpC-9zD8Ww==/video.api.reactnative.livestream.example-k3-VntwSyovRnzc5_56SLw==/base.apk]
      #14 pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #15 pc 000000000031f806  /system/framework/framework.jar
      #16 pc 000000000020a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #17 pc 000000000031fae0  /system/framework/framework.jar
      #18 pc 000000000200ece0  /memfd:jit-cache (deleted) (android.os.Handler.dispatchMessage+272)
      #19 pc 0000000002038b48  /memfd:jit-cache (deleted) (android.os.Looper.loopOnce+1480)
      #20 pc 0000000002016878  /memfd:jit-cache (deleted) (android.os.Looper.loop+696)
      #21 pc 00000000002ca9e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #22 pc 00000000002ee6b8  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+320) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #23 pc 000000000040ade4  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+820) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #24 pc 000000000076d4b8  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+3812) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #25 pc 00000000002c5014  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #26 pc 00000000004490d8  /system/framework/framework.jar
      #27 pc 000000000027d840  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.3351068054637636664)+644) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #28 pc 000000000027c9e8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1176) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #29 pc 00000000002d4178  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #30 pc 00000000002ca764  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #31 pc 000000000030e980  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+156) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #32 pc 00000000003c1db4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+380) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #33 pc 00000000004578ec  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+992) (BuildId: 34e3dd028e2e682b63a512d6a4f1b5eb)
      #34 pc 00000000000f0d34  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: e1f31041be009cf8613d6678cdccd160)
      #35 pc 000000000008d57c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: e1f31041be009cf8613d6678cdccd160)
`

**Comment by ThibaultBee** [comment]
Hi,

The example application crashes because it does not request permissions. Is that your issue?

**Comment by lewatt23** [comment]
Hello, 
Sorry for the late reply, actaully the permission are okay, but as soon as i start the stream i get the error above, i don't have any hint on what is causing it, i used the example repo, if you have another repo  i can test with it again. but so far i tested the  example repo with 2 devices android 12 and 7, but are giving me the error i mentioned above.

**Comment by ThibaultBee** [comment]
Could you test with v1.1.2?

**Comment by ThibaultBee** [comment]
No news: closing.
Please, feel free to reopen if the bug still exists

**Comment by tarun-showday** [comment]
Still crashing

**Comment by rennard** [comment]
I'm having the same issue
