### ISSUE TITLE
Front camera as default not working

### ISSUE THREAD

**Issue by cavoco** [apivideo/api.video-reactnative-live-stream#26]
**Describe the bug**
Using the example app when I set the default camera to be 'front' the back camera is still selected by default. I have to double tap the switch camera button to get it in sync and work normally.

**To Reproduce**
1. Change :`const [camera, setCamera] = React.useState<'front' | 'back'>('back');` 
to:  `const [camera, setCamera] = React.useState<'front' | 'back'>('front');`
2. Tap the switch camera  button.
3. Nothing happens
4. Tap switch camera button again.
5. Works as expected.

**Expected behavior**
The app starts up with the front facing camera.

**Smartphone (please complete the following information):**
 - Device: iPhone 8 
 - OS: iOS 14.6

**Comment by ThibaultBee** [comment]
Hi,

This issue have been fixed in v1.1.2.
