### ISSUE TITLE
Crashing/ANR during live stream on some devices

### ISSUE THREAD

**Issue by sadashivsinha** [apivideo/api.video-reactnative-live-stream#27]
**Describe the bug**
Getting these error and app is getting crash or ANR on some devices, other devices working fine.

1.
io.github.thibaultbee.streampack.internal.encoders.VideoMediaCodecEncoder$CodecSurface.stopStream (VideoMediaCodecEncoder.kt:247)

2.
main(native)
video.api.rtmpdroid.Rtmp.nativeConnectStream (Native method)

3.
lib.so
Crashed: Thread #1
SIGSEGV 0x0000000000000018

**To Reproduce**
1. Start live streaming (issue happening on OnePlus 6 and OnePlus Nord, but working fine in OnePlus Nord 2 CE)

**Expected behavior**
It should live stream properly without any ANR or crash

**Smartphone (please complete the following information):**
 - Device: OnePlus 6 and OnePlus Nord
 - OS: Android 10/11
 - Version [Latest]

**Comment by ThibaultBee** [comment]
Hi,

Unfortunately we don't have these smartphones to reproduce the issue. Could you provide a full logcat please?
Does it happen randomly?
Juste want to be sure: it does happen when you call `startStreaming`?

**Comment by sadashivsinha** [comment]
Yes its 3 different issues but all are related to live stream itself.
Here is full logcat of all 3 issues.


main (waiting)
tid=1 systid=28723
Triggered ANR
Root blocking
sun.misc.Unsafe.park (Native method)
java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
java.util.concurrent.FutureTask.awaitDone (FutureTask.java:450)
java.util.concurrent.FutureTask.get (FutureTask.java:192)
io.github.thibaultbee.streampack.internal.encoders.VideoMediaCodecEncoder$CodecSurface.stopStream (VideoMediaCodecEncoder.kt:247)
io.github.thibaultbee.streampack.internal.encoders.VideoMediaCodecEncoder.stopStream (VideoMediaCodecEncoder.kt:112)
io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.stopStreamImpl (BaseStreamer.kt:329)
io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.stopStream (BaseStreamer.kt:315)
video.api.livestream.ApiVideoLiveStream.stopStreaming (ApiVideoLiveStream.kt:264)
video.api.reactnative.livestream.ReactNativeLiveStreamView.stopStreaming$api_video_react_native_livestream_release (ReactNativeLiveStreamView.kt:115)
video.api.reactnative.livestream.ReactNativeLiveStreamViewManager.receiveCommand (ReactNativeLiveStreamViewManager.kt:38)
video.api.reactnative.livestream.ReactNativeLiveStreamViewManager.receiveCommand (ReactNativeLiveStreamViewManager.kt:13)
com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand (NativeViewHierarchyManager.java:831)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.executeWithExceptions (UIViewOperationQueue.java:323)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:879)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1026)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:47)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1086)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1519)
android.view.Choreographer.doCallbacks (Choreographer.java:1319)
android.view.Choreographer.doFrame (Choreographer.java:1005)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1506)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:265)
android.app.ActivityThread.main (ActivityThread.java:8360)
java.lang.reflect.Method.invoke (Native method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:632)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1049)



2.
video.api.rtmpdroid.Rtmp.nativeConnectStream (Native method)
video.api.rtmpdroid.Rtmp.connectStream (Rtmp.kt:93)
io.github.thibaultbee.streampack.ext.rtmp.internal.endpoints.RtmpProducer.startStream (RtmpProducer.kt:75)
io.github.thibaultbee.streampack.streamers.bases.BaseStreamer.startStream (BaseStreamer.kt:277)
io.github.thibaultbee.streampack.streamers.live.BaseCameraLiveStreamer.startStream$suspendImpl (BaseCameraLiveStreamer.kt:97)
io.github.thibaultbee.streampack.streamers.live.BaseCameraLiveStreamer$startStream$1.invokeSuspend (BaseCameraLiveStreamer.kt)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
kotlinx.coroutines.EventLoopImplBase.processNextEvent (EventLoop.common.kt:274)
kotlinx.coroutines.BlockingCoroutine.joinBlocking (Builders.kt:85)
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking (Builders.kt:59)
kotlinx.coroutines.BuildersKt.runBlocking (unavailable:1)
kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default (Builders.kt:38)
kotlinx.coroutines.BuildersKt.runBlocking$default (unavailable:1)
video.api.livestream.ApiVideoLiveStream.startStreaming (ApiVideoLiveStream.kt:252)
video.api.livestream.ApiVideoLiveStream.startStreaming$default (ApiVideoLiveStream.kt:241)
video.api.reactnative.livestream.ReactNativeLiveStreamView.startStreaming$api_video_react_native_livestream_release (ReactNativeLiveStreamView.kt:106)
video.api.reactnative.livestream.ReactNativeLiveStreamViewManager.receiveCommand (ReactNativeLiveStreamViewManager.kt:36)
video.api.reactnative.livestream.ReactNativeLiveStreamViewManager.receiveCommand (ReactNativeLiveStreamViewManager.kt:13)
com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand (NativeViewHierarchyManager.java:831)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.executeWithExceptions (UIViewOperationQueue.java:323)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:879)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1026)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:47)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1086)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1519)
android.view.Choreographer.doCallbacks (Choreographer.java:1319)
android.view.Choreographer.doFrame (Choreographer.java:1005)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1506)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:265)
android.app.ActivityThread.main (ActivityThread.java:8360)
java.lang.reflect.Method.invoke (Native method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:632)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1049)




3.
Crashed: Thread #1
SIGSEGV 0x0001ac0000000100
0
libhwui.so
(Missing UUID ca8b2c42716a0a9f17382be819c89881)
2
libhwui.so
(Missing UUID ca8b2c42716a0a9f17382be819c89881)
Thread #2
0
libc.so
(Missing UUID 0abcff352f27dd1f0347c6a1e13d290b)
1
libc.so
(Missing UUID 0abcff352f27dd1f0347c6a1e13d290b)

**Comment by sadashivsinha** [comment]
I cant send adb logcat as I am sending errors from users from crashylitics

**Comment by ThibaultBee** [comment]
Ok, I understand.
We can't do much about it... We will read the code for the first and second issues to check if something is wrong but we cannot garanty anything.
About the third one, there is a crash in libhwui and libc which are system libraries. At the state, we can't do anything about that.

**Comment by ThibaultBee** [comment]
Hi,

What version do you use?

About the first issue, the `CodecSurface` `Future` does not answer because there is a lock in the encoder provider.  I can get the `Future` to timeout but I would like to understand how it can happen.

About the second issue, there is a try/catch block around startStream/nativeConnectStream, it should not crash. See https://github.com/apivideo/api.video-reactnative-live-stream/blob/6ce902bf5eed66c9383b97d3b10a0395e8e9869e/android/src/main/java/video/api/reactnative/livestream/ReactNativeLiveStreamView.kt#L103

**Comment by sadashivsinha** [comment]
I am using latest version v1.1.0

It happens on some devices, sometimes ANR and sometimes crash.

Steps :-
1. Start livestream
2. Wait 10-15 seconds
3. Crash or ANR


Sometimes crash happens at start itself and sometimes at stop.
