### ISSUE TITLE
A problem occurred configuring project ':@api.video/react-native-livestream'.

### ISSUE THREAD

**Issue by Lunziyuan** [apivideo/api.video-reactnative-live-stream#29]
react-native: v0.61.5
@api.video/react-native-livestream: v.1.1.0

> The project name '@api.video/react-native-livestream' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/6.1.1/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).

**Comment by ThibaultBee** [comment]
Please, reopen this issue if you got any news.
