### ISSUE TITLE
Streaming status

### ISSUE THREAD

**Issue by Geoffrey63** [apivideo/api.video-reactnative-live-stream#3]
Hi, 
Currently, the `ref.current?.startStreaming();` method start the stream from the LivestreamView but does give any feedback on the real status of the stream.
Is this a feature you plan to add to the SDK ? 
If not, what would be the best way to handle it ?
Thank you for your reply.

**Comment by RomainPetit1** [comment]
Hi @Geoffrey63,

Just to be sure what you are asking, you want to get info if the stream status is connected or failed ? 
If so yes we will add this soon, for now you can't access this status. On Android you can get some static logs but that's all for now.

**Comment by Geoffrey63** [comment]
Hi @RomainPetit1, 

Yes, I would like to get a real feedback of the livestream status (confirmation that the live session has started and that my user is connected). 
I could monitor the "broadcasting" field of the live object through the API (changing from "false" to "true) but I don't know if it's enough to confirm the "link" between my app and the stream.

**Comment by naudej** [comment]
I see that there is an open PR for the onStatusChange callback, will this also return errors? We currently have issues with streaming on Android (works on iOS). Nothing is happening even though we have permissions enabled (according to the docs) and the rest of the camera and audio based features from the app works as is

**Comment by ThibaultBee** [comment]
Hi @naudej, Hi @Geoffrey63,
With [Release 0.2.0](https://github.com/apivideo/api.video-reactnative-live-stream/releases/tag/0.2.0) you can have a feedback on stream events.

In LivestreamView, there are 3 new callbacks:
```
        onConnectionSuccess={() => {
          //do what you want
        }}
        onConnectionFailed={(e) => {
          //do what you want
        }}
        onDisconnect={() => {
          //do what you want
        }}
```
