### ISSUE TITLE
[Android] Error while updating property...

### ISSUE THREAD

**Issue by Qweest** [apivideo/api.video-reactnative-live-stream#30]
Hey guys!
I have this error on Android device when trying to render `LiveStreamView` component. Also I had the same error but it said "Error while updating property 'audio'". I can't figure out what the problem is. Did anyone encounter with it? My RN version is 0.69.
**BTW: I am using Apple MacBook with M1 chip**

<img width="357" alt="Screen Shot 2022-07-21 at 3 39 06 PM" src="https://user-images.githubusercontent.com/34643993/180227605-a4d1fd44-53cd-4dec-8092-6116b58084cd.png">

Here is my component source code (basically the same as example in README, but with some permissions settings):

```
const App = () => {
  const ref = useRef(null);
  const [streaming, setStreaming] = useState(false);
  const [initialized, setInitialized] = useState(false);

  const init = async () => {
    const hasMicPermission = await checkMicrophonePermission();
    const hasCamPermission = await checkCameraPermission();

    const micPermissionGranted =
      hasMicPermission ||
      (await requestMicrophonePermission()) === RESULTS.GRANTED;

    const camPermissionGranted =
      hasCamPermission || (await requestCameraPermission()) === RESULTS.GRANTED;

    if (micPermissionGranted && camPermissionGranted) {
      setInitialized(true);
    }
  };

  useEffect(() => {
    init();
  }, []);

  if (!initialized) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator />
      </View>
    );
  }

  return (
    <View style={{ flex: 1, alignItems: 'center' }}>
      <LiveStreamView
        style={{ flex: 1, backgroundColor: 'black', alignSelf: 'stretch' }}
        ref={ref}
        camera="back"
        video={{
          fps: 30,
          resolution: '720p',
          bitrate: 2*1024*1024, // # 2 Mbps
        }}
        audio={{
          bitrate: 128000,
          sampleRate: 44100,
          isStereo: true,
        }}
        isMuted={false}
        onConnectionSuccess={() => {
          //do what you want
        }}
        onConnectionFailed={e => {
          //do what you want
        }}
        onDisconnect={() => {
          //do what you want
        }}
      />
      <View style={{ position: 'absolute', bottom: 40 }}>
        <TouchableOpacity
          style={{
            borderRadius: 50,
            backgroundColor: streaming ? 'red' : 'white',
            width: 50,
            height: 50,
          }}
          onPress={() => {
            if (streaming) {
              ref.current?.stopStreaming();
              setStreaming(false);
            } else {
              ref.current?.startStreaming('*****');
              setStreaming(true);
            }
          }}
        />
      </View>
    </View>
  );
};

export default App;
```

**Comment by Qweest** [comment]
Looks like the issue was because of conflict with flipper, so I decided to remove it for my Android app

**Comment by bachngocnhat** [comment]
> Hey guys! I have this error on Android device when trying to render `LiveStreamView` component. Also I had the same error but it said "Error while updating property 'audio'". I can't figure out what the problem is. Did anyone encounter with it? My RN version is 0.69. **BTW: I am using Apple MacBook with M1 chip**
> 
> <img alt="Screen Shot 2022-07-21 at 3 39 06 PM" width="357" src="https://user-images.githubusercontent.com/34643993/180227605-a4d1fd44-53cd-4dec-8092-6116b58084cd.png">
> 
> Here is my component source code (basically the same as example in README, but with some permissions settings):
> 
> ```
> const App = () => {
>   const ref = useRef(null);
>   const [streaming, setStreaming] = useState(false);
>   const [initialized, setInitialized] = useState(false);
> 
>   const init = async () => {
>     const hasMicPermission = await checkMicrophonePermission();
>     const hasCamPermission = await checkCameraPermission();
> 
>     const micPermissionGranted =
>       hasMicPermission ||
>       (await requestMicrophonePermission()) === RESULTS.GRANTED;
> 
>     const camPermissionGranted =
>       hasCamPermission || (await requestCameraPermission()) === RESULTS.GRANTED;
> 
>     if (micPermissionGranted && camPermissionGranted) {
>       setInitialized(true);
>     }
>   };
> 
>   useEffect(() => {
>     init();
>   }, []);
> 
>   if (!initialized) {
>     return (
>       <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
>         <ActivityIndicator />
>       </View>
>     );
>   }
> 
>   return (
>     <View style={{ flex: 1, alignItems: 'center' }}>
>       <LiveStreamView
>         style={{ flex: 1, backgroundColor: 'black', alignSelf: 'stretch' }}
>         ref={ref}
>         camera="back"
>         video={{
>           fps: 30,
>           resolution: '720p',
>           bitrate: 2*1024*1024, // # 2 Mbps
>         }}
>         audio={{
>           bitrate: 128000,
>           sampleRate: 44100,
>           isStereo: true,
>         }}
>         isMuted={false}
>         onConnectionSuccess={() => {
>           //do what you want
>         }}
>         onConnectionFailed={e => {
>           //do what you want
>         }}
>         onDisconnect={() => {
>           //do what you want
>         }}
>       />
>       <View style={{ position: 'absolute', bottom: 40 }}>
>         <TouchableOpacity
>           style={{
>             borderRadius: 50,
>             backgroundColor: streaming ? 'red' : 'white',
>             width: 50,
>             height: 50,
>           }}
>           onPress={() => {
>             if (streaming) {
>               ref.current?.stopStreaming();
>               setStreaming(false);
>             } else {
>               ref.current?.startStreaming('*****');
>               setStreaming(true);
>             }
>           }}
>         />
>       </View>
>     </View>
>   );
> };
> 
> export default App;
> ```


did you find a way to fix it? please share me, i am having the same problem
