### ISSUE TITLE
on running in expo it gives error of Invariant Violation: requireNativeComponent: "ReactNativeLiveStreamView" was not found in the UIManager.

### ISSUE THREAD

**Issue by jitanuswara** [apivideo/api.video-reactnative-live-stream#31]
**Describe the bug**

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ThibaultBee** [comment]
`expo` is not supported yet but you can use `yarn`.

Please fill properly the issue templates.

**Comment by BlueBazze** [comment]
It looks like you havent built your dev client with this package installed.

For future reference.
The package works fine with expo. No adjustment needed.
Expo have made EAS. Which makes it very easy to include any react native dependency into your project.
Basically they have a package called expo-dev-client  which is basically just the expo go app, but during building it will include any native code installed in your dependencies.

Meaning to install this package with expo.
Make sure you know how to use EAS.
1. `yarn add @api.video/react-native-livestream`
2. Create a component using react-native-livestream
3. `eas build --profile development`
Now you will get a "custom" expo go app which has included the native code of this package.
