### ISSUE TITLE
App crash on Android phones when navigate back from camera screen

### ISSUE THREAD

**Issue by tarun-showday** [apivideo/api.video-reactnative-live-stream#35]
**Describe the bug**
App crash when I navigate to another screen from the camera screen(where this lib is used).

**To Reproduce**
1. Open the camera screen
2. Press back
3. And it crashed 

**Expected behavior**
It should not crash the app. on moving between screen.

**Crash logs**
Here is the full crash logs details provided by the sentry:
https://gist.github.com/tarun-showday/62bbd2cbc4b938440808928b02979d87 

**Smartphone (please complete the following information):**
 - Device: Mi A1
 - OS:  Android 9 

**Additional context**
It's working on some of the android device but in some of the device which I have mentioned and vivo y1 also it's crashing all the time.

**Comment by ThibaultBee** [comment]
Duplicated. See  #33
