### ISSUE TITLE
Android app crash on the camera screen

### ISSUE THREAD

**Issue by tarun-showday** [apivideo/api.video-reactnative-live-stream#36]
**Describe the bug**
Jump to camera screen crash the app on some of the android phones 

**To Reproduce**
1. Jump to camera screen 
2. It will load the camera and then in a second it crashed

**Expected behavior**
It should not crash the app 

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy Note 9 (SM-N960U)
 - OS: Android 10 
 - API stream SDK version: 1.2.0

**Crash logs**
https://gist.github.com/tarun-showday/616a3b4454b4137d4e94a0bfd7bffeaa

**Comment by ThibaultBee** [comment]
Hi,
The crash you have is:
```
Thread 0 Crashed:
0   libart.so                       0x7cdcdcdfa4        0x7cdca09000 + 536281407396
1   libandroid_runtime.so           0x7d62152f08        0x7d61fd1000 + 538516467464
2   boot-framework.oat              0x718198c8          0x714fb000 + 1904318664
```

There is nothing related to this library, so we can't be really helpfull here. If you find another relevant information I will reopen the issue.

Best regards
