### ISSUE TITLE
Is this for use with api.video exclusively?

### ISSUE THREAD

**Issue by shawarmaz** [apivideo/api.video-reactnative-live-stream#37]
Getting started contains a token, is this usable without api.video ?

**Comment by RomainPetit1** [comment]
Hello @shawarmaz, Yes you can use it without api.video. You must specify your own rmtp url in the startStreaming method as mentioned in the readme.

```
  // streamKey: your live stream RTMP key
  // url: RTMP server url, default: rtmp://broadcast.api.video/s
  startStreaming: (streamKey: string, url?: string) => void;
```

**Comment by ThibaultBee** [comment]
Hi @shawarmaz,

To be more precise, this library is tested with both api.video and with FFplay (from FFmpeg).
