### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ReactNativeLivestreamView" was not found in the UIManager.

### ISSUE THREAD

**Issue by kunal047** [apivideo/api.video-reactnative-live-stream#4]
Setting up the example throws the "ReactNativeLivestreamView" was not found in the UIManager error in Android.

**Comment by olivierapivideo** [comment]
Hi Kunal,

Can you tell us how you start the example app?
The following should work (in the `example/` folder):
```bash
yarn
yarn run android
```

**Comment by olivierapivideo** [comment]
I'm closing this one because it's getting a little old, feel free to open a new one if needed!

**Comment by slodhi786** [comment]
Getting similar exception. I am already using NodeMediaClient but wanted to replace the plugin to @api.video. 

![image](https://user-images.githubusercontent.com/71716355/169662434-663e2d56-1ab3-4f76-b9e6-19a4f33c7e8d.png)

![image](https://user-images.githubusercontent.com/71716355/169662476-f5cefd7a-12d4-49f2-b229-a672b42d8af6.png)

![image](https://user-images.githubusercontent.com/71716355/169662386-63e93c2c-6445-487a-a7fd-63c8d16b9193.png)

**Comment by ThibaultBee** [comment]
Hi,

This is a RN issue: see https://github.com/facebook/react-native/issues/31572
In the meantime, I see that you are using `rtmpServerUrl` and `liveStreamKey`. Since 1.0.0, these fields don't exist. RTMP URL and Stream key are passed by `startStreaming`.

Regards
