### ISSUE TITLE
README example freezes after on start/stop/start

### ISSUE THREAD

**Issue by eightyfive** [apivideo/api.video-reactnative-live-stream#40]
Running the README example. After I `stopStreaming` the first time, the "camera view" freezes on next `startStreaming`.

This is how it goes:

1. Mount screen ✅
2. Do not start streaming yet
3. Move camera around, the "camera view" works ✅
4. Start streaming
5. onConnecttionSuccess event is fired ✅
6. Move camera around, the "camera view" works ✅
7. Stop streaming
8. onDisconnect event is fired ✅
9. Move camera around, the "camera view" works ✅
10. Start streaming again
11. onConnecttionSuccess event is fired ✅
12. "Camera view" does NOT work ❌
13. Stop streaming
14. Button changes color red --> white (so not the screen freezing) ✅
15. onDisconnect event is NOT fired ❌

No JS errors, no crash. Just the "camera view" freezing.

Any help/hint would be appreciated 🙏

**Comment by ThibaultBee** [comment]
On which phone do you have the issue?

**Comment by eightyfive** [comment]
Same as other issue: Samsung Galaxy J Prime (Android).

**Comment by eightyfive** [comment]
I will troubleshoot more tomorrow.

I'm actually having another issue on top of that: I cannot stream my custom `rmtps` URL + `stream_key`.

I can see "Live" on the player side, but the video/live stream is all black.

It might all be related.

**Comment by eightyfive** [comment]
> When 12. or 13. do you have a stream on your server side?

That's what I am not able to confirm yet.

**Comment by ThibaultBee** [comment]
What player/server do you use?

**Comment by eightyfive** [comment]
Server: mix of Nimble + Dolby.io 

Player: millicast

**Comment by eightyfive** [comment]
Works well on a newer device, but with the same Android version (Oreo) on both devices. Strange.

**Comment by ThibaultBee** [comment]
Please retest with v1.2.2
