### ISSUE TITLE
v1.2.1 Stream Url Problem

### ISSUE THREAD

**Issue by mehmetcansahin** [apivideo/api.video-reactnative-live-stream#41]
**Describe the bug**
There is a problem in the Steam Key section when opening a live broadcast in the application. The stream url information to the RTMP Server side is `live/ffd83834-f73e-459e-a0f5-80964700f2f9live1flashverFMLE/3.0 (compatible; FMSc/1.0)1.0)/ffd83834-f73e-459e-a0f5-80964700f2f`. It comes to RTMP server repetitively and with different information added to it. 

**To Reproduce**
1. Create a new project v1.2.1
2. Use custom rtmp server (e.g.: srs, zlmediakit, livego etc.)
3. Live stream is not started because stream url is not parsable

**Expected behavior**
Stream url coming to server now like this => `live/ffd83834-f73e-459e-a0f5-80964700f2f9live1flashverFMLE/3.0 (compatible; FMSc/1.0)1.0)/ffd83834-f73e-459e-a0f5-80964700f2f`
expected like this => `live/ffd83834-f73e-459e-a0f5-80964700f2f9`

**Screenshots**
![image](https://user-images.githubusercontent.com/2010841/199944830-6eb5e27d-cac7-49d1-b84f-84a807886a2c.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android 12.0

**Additional context**
There weren't a bug in 1.2.0 like this. It was working properly.

**Comment by ThibaultBee** [comment]
Hi,

RTMP url is very often:
`rtmp://ip/app/streamkey?live=1&flashVer=FMLE/3.0 (compatible; FMSc/1.0)&param=value`
`live=1` was already there in v1.2.0.

Does it lead to an issue on your side?

**Comment by mehmetcansahin** [comment]
We saw that it is due to the streaming server we use. We have done many rtmp server tests (e.g.: srs, zlmediakit, livego, node media server), for now we only got healthy results with nginx-rtmp-module.
