### ISSUE TITLE
audiosamplerate not included on iOS

### ISSUE THREAD

**Issue by daveisfera** [apivideo/api.video-reactnative-live-stream#51]
**Describe the bug**
The `onMetaData` from iOS has `audiodatarate` but not `audiosamplerate` (using the info parsed in #47 )

**To Reproduce**
1. Send video with iOS
2. Parse `onMetaData` message
3. Observe `audiodatarate` is included but `audiosamplerate` is not

**Expected behavior**
`audiosamplerate` is also included with `audiodatarate`

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: 16.1.2
 - Browser: Safari
 - Version: 16.1

**Additional context**
Knowing the sample rate of the audio allows proper handling of the audio stream that's coming in

**Comment by ThibaultBee** [comment]
Hi,
Yes you are right: see https://github.com/shogo4405/HaishinKit.swift/blob/ca2505a06762da5909d865b796f77c8e27cfdcc5/Sources/RTMP/RTMPStream.swift#L440

Could you add a direct issue there?

Are you aware that you can also find this information in the `AudioTagHeader` (it is called `SoundRate`)?

**Comment by daveisfera** [comment]
Opened an issue with upstream

**Comment by daveisfera** [comment]
Can HaishinKit be [upgraded to 1.4.0](https://github.com/shogo4405/HaishinKit.swift/releases/tag/1.4.0) to get this fix?

**Comment by ThibaultBee** [comment]
Hi,

Could you check that the `main` branch does fix the issue?

**Comment by rranjan14** [comment]
@daveisfera Did you try with `pod install --repo-update`?

**Comment by daveisfera** [comment]
I got that installed and `audiosamplerate` is now included, but it's `0` so that's incorrect and problematic. I assume that's an issue to check with the lower level module, right?

**Comment by ThibaultBee** [comment]
Indeed it is an issue with HaishinKit. I could made a workaround but I am afraid of the side effects as it may changes sample rate on devices that does not support it.
The next release might not fix this issue.

**Comment by ThibaultBee** [comment]
I push new HaishinKit version to the `main` branch.
Could you check it is fixed?

**Comment by daveisfera** [comment]
I verified that this works. Thanks for getting it out there!
