### ISSUE TITLE
Front camera got freeze after 2 to 3 seconds

### ISSUE THREAD

**Issue by shanmukhav-newzera** [apivideo/api.video-reactnative-live-stream#54]
**Describe the bug**
Front camera is getting struck in android after opening front camera and screen got freeze, Where as back camera is working with out getting struck

In IOS both cameras were working.

I tested on devices android 13 and android 9, In both devices front camera got struck

**Comment by ThibaultBee** [comment]
Hi,
This is a duplicated issue. See https://github.com/apivideo/api.video-reactnative-live-stream/issues/44 instead.

**Comment by shanmukhaVoggu** [comment]
> Hi, This is a duplicated issue. See #44 instead.

Thanks for the reply,

But https://github.com/apivideo/api.video-reactnative-live-stream/issues/44 is about slow mount of the camera, But my issue is camera got freezed completely atleast greater than 10 mins even in my android 13 mobile

**Comment by ThibaultBee** [comment]
Oops, sorry, I read too quickly. Your issue is on Android, the other one is on iOS.
Could you add more information to your issue? (devices, way to reproduce it easily)

**Comment by ThibaultBee** [comment]
Hi,
I tried but I can't reproduce the issue with my device.
Could you get the logcat of the application? There might be few interested logs there.

**Comment by ThibaultBee** [comment]
Stall issue.
Please reopen this issue if you have additional info.
