### ISSUE TITLE
iOS: Live Stream start in mirror mode.

### ISSUE THREAD

**Issue by codal-mpawar** [apivideo/api.video-reactnative-live-stream#58]
**To Reproduce**
1. Open the app.
2. Start the live stream.
3. See the camera view 

**Expected behavior**
Always display non-mirror mode.

**Screenshots**
You can refer this video
[here is video](https://github.com/apivideo/api.video-reactnative-live-stream/issues/57#issuecomment-1401702660)

**Smartphone (please complete the following information):**
 Smartphone (please complete the following information):

Device: iPhone 11 pro max
- iPhone OS Version: 16.2
- Xcode version 14.2
- Mac OS: Monterey 12.6

Additional context
"@api.video/react-native-livestream": "v1.2.3"
"react": "16.13.1",
"react-native": "0.64.2",
"react-native-orientation-locker": "^1.4.0",

**Comment by codal-mpawar** [comment]
@ThibaultBee Can you please check once.

**Comment by codal-mpawar** [comment]
@ThibaultBee Any update on this?

**Comment by codal-mpawar** [comment]
@MarDi66 @pfcodes @ThibaultBee Any update on this?

**Comment by tarun-showday** [comment]
this behaviour is changed in the latest version only, I have checked in **1.2.1** and it was working fine.

**Comment by codal-mpawar** [comment]
@tarun-showday thanks for your reply.
But you have any idea about fix?

**Comment by codal-mpawar** [comment]
@MarDi66 @pfcodes @ThibaultBee Can you please update here anything. because, we are blocked due to this issue.

**Comment by ThibaultBee** [comment]
Hi,
We are working on lot of projects, so we might handle issues quickly.
Also, the code is open source, so you can also look at the issue to help us :)

The cameras streams are captured in mirror? All the cameras? Is that what you are saying? 
Is it really this critical?

**Comment by codal-mpawar** [comment]
@ThibaultBee Not much critical. 

You are right, We can do but you have already an idea about the code. It's taking time to fix from our side. But sure we try to fix it.

**Comment by ThibaultBee** [comment]
The reason I comment it is because the native library has changed its behaviours:
now:
- the camera has changed
- mirror the view
(before you could do the opposite)
So the application user will see the transition between the non mirror to mirror.

Are you okay with that?

**Comment by codal-mpawar** [comment]
If it's the case, Then @ThibaultBee Can we add a boolean condition for mirror mode and nonmirror mode? So in that case client decide in which mode stream needs to be displayed. Let me know what're your thoughts.

**Comment by ThibaultBee** [comment]
Not fond of adding a flag to fix an issue in the sublibrary.
I hope this will fix it: https://github.com/shogo4405/HaishinKit.swift/commit/18132ec3c31c963a5cfcebe338e621312980987c

**Comment by codal-mpawar** [comment]
@ThibaultBee May be its work, Can you update our package.

**Comment by codal-mpawar** [comment]
@ThibaultBee We are waiting for your response.

**Comment by gokugen** [comment]
Any updates ?

**Comment by ThibaultBee** [comment]
I push new HaishinKit version to the `main` branch.
Could you check it is fixed?

**Comment by codal-mpawar** [comment]
@ThibaultBee working fine. please publish the repo. thanks for your efforts.

**Comment by codal-mpawar** [comment]
@ThibaultBee Reminder for publish the latest code repo.
