### ISSUE TITLE
Android: Camera view is stretching out.

### ISSUE THREAD

**Issue by codal-mpawar** [apivideo/api.video-reactnative-live-stream#59]
### Version

v1.2.3

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

Any android device.
I have
Samsung galaxy s10+
Samsung galaxy A20
Samsung galaxy F62

### Is it reproducible in the example application?

Yes

### RTMP Server

rtmps://global-live.mux.com:443/app

### Reproduction steps

1. Open the app
2. Start the live stream in landscape mode.
3. See the camera view its stretching the view. 

### Expected result

Not stretching out the view.

### Actual result

stretching out the view.

### Additional context

"react": "16.13.1",
"react-native": "0.64.2",
"@api.video/react-native-livestream": "^1.2.3",
"react-native-orientation-locker": "^1.4.0",

### Relevant logs output

```shell
-
```

**Comment by codal-mpawar** [comment]
here is code @ThibaultBee 
`
<LiveStreamView
            style={{
                height: height,
                width: width
            }}
            ref={getVideoRef}
            camera={isBackCamera ? Config.Camera.back : Config.Camera.front}
            video={Config.VideoConfig}
            audio={Config.AudioConfig}
            isMuted={false}
            onConnectionSuccess={() => undefined}
            onConnectionFailed={(event) => {
            onDisconnect={() => undefined}
        />
`

**Comment by ThibaultBee** [comment]
Hi,

What is strech? The playback on your server or the camera preview?

What is your video configuration? and `height` and `width`?

**Comment by codal-mpawar** [comment]
The preview is good on the server side. The camera was stretching out on the client's side.

### **Device height and width**
```javascript
height: 384
width: 772.6222222222223
```

### **here is the config:**
```javascript
const Config = {
    Camera: { back: 'back', front: 'front' },
    VideoConfig: {
        fps: 24,
        resolution: '720p',
        bitrate: 1 * 1024 * 1024,
        gopDuration: 1
    },
    AudioConfig: {
        bitrate: 128000,
        sampleRate: 44100,
        isStereo: true
    }
};
```

**Comment by ThibaultBee** [comment]
Hi,
Could you make a screenshot?
Don't you have the same issue on iOS (screenshot)?

**Comment by codal-mpawar** [comment]
@ThibaultBee I am facing an issue in android only. not on iOS.

Please check the below screenshot.
![issue](https://user-images.githubusercontent.com/46340921/218754164-cfb4060f-6bdc-4709-a050-3738cb841e12.jpg)

We will try with the aspect ratio and update you soon.

**Comment by codal-mpawar** [comment]
@ThibaultBee We are going with an aspect ratio and it's working fine. Thanks for your valuable input and appreciate it. we can close this issue.

**Comment by tamdvyounetgroup** [comment]
The issue is still on the first open camera on Android. the issue has hide when changing to the back camera and comeback

**Comment by codal-mpawar** [comment]
@tamdvyounetgroup Can you please share something like what you do
