### ISSUE TITLE
[Bug]: Bitrate is not set correctly on initial render

### ISSUE THREAD

**Issue by Pitros** [apivideo/api.video-reactnative-live-stream#60]
### Version

v1.2.3

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

Samsung Galaxy S20 - Android 13 - wrong initial bitrate
Samsung Galaxy S9 - Android 10 - works fine

### Is it reproducible in the example application?

Yes

### RTMP Server

restream.io

### Reproduction steps

1. Start streaming with some bitrate (eg. 0.5Mb)
2. On any page that shows bitrate (eg. restram.io) bitrate will not match
3. Change bitrate in video params object via code while streaming is active or with any controls
4. Bitrate will change to valid one (eg. 1Mb)

### Expected result

Bitrate is accepted 

### Actual result

For params below streaming is started with 2.6Mbps
```
{
  fps: 30,
  resolution: '720p',
  bitrate: 1 * 1024 * 1024, // # 2 Mbps
}
```

### Additional context

Works fine on S9 with Android 10.

**Comment by ThibaultBee** [comment]
Hi,

As it seems device dependent, it is going to be difficult to test.
I will try to recheck with my Pixel 4a.

**Comment by gokugen** [comment]
Same issue here with a S9 on android 10.

I saw that it depends on whether we use the front or back camera too.
When i use the phone's back camera with a bitrate of 2000000 and a gopDuration equal to 1 I can normaly stream but if I try with the front camera I can't view my stream on my NodeMediaServer.

**Comment by ThibaultBee** [comment]
Stalled issue. Not enough information to reproduce it.
Please reopen the issue if you got new info.
