### ISSUE TITLE
[Bug]: LiveStreamView Warp

### ISSUE THREAD

**Issue by jpv3dts** [apivideo/api.video-reactnative-live-stream#64]
### Version

v1.2.3

### Which operating systems have you used?

- [X] Android
- [X] iOS

### Environment that reproduces the issue

* Samsung galaxy A12 (Android 13)
* Google Pixel 6 Pro emulator (Android 13)
* iPhone 11 (iOS 16.4.1)

### Is it reproducible in the example application?

Not tested

### RTMP Server

AMS

### Reproduction steps

Create app with a LiveStreamView.

### Expected result

The LiveStreamView scales to the containing view while maintaining the camera's aspect ratio.

### Actual result

The LiveStreamView warps.

**Comment by ThibaultBee** [comment]
This issue is supposed to be fixed with 2.0.0.
Could you test with 2.0.0?

**Comment by ThibaultBee** [comment]
Stall issue.
Please reopen if you have new info.
