### ISSUE TITLE
[Bug]: Add overlay on on going stream e.g water mark or real time data like scoreboard of sport 

### ISSUE THREAD

**Issue by makani20** [apivideo/api.video-reactnative-live-stream#71]
### Version

v1.2.3

### Which operating systems have you used?

- [X] Android
- [X] iOS

### Environment that reproduces the issue

iOS and Android

### Is it reproducible in the example application?

Yes

### RTMP Server

Youtube Streaming server

### Reproduction steps

we can not add any view middle of <LiveStreamView/> component 

### Expected result

it should be visible 

### Actual result

not visible other overlay view

**Comment by ThibaultBee** [comment]
Hi,

Do you mean an overlay of the preview? or in the stream?

**Comment by makani20** [comment]
or in the stream-> i want to add scoreboard for live sports stream

**Comment by ThibaultBee** [comment]
Ok, I see. It is a feature OBS have.
Implementation of something like this is really complex and we don't have the bandwidth to tackle this.
We won't work on it any day soon but we will gladly review a PR if needed.
