### ISSUE TITLE
[Feat]: Capture Frames

### ISSUE THREAD

**Issue by razamsalem** [apivideo/api.video-reactnative-live-stream#75]
### Version

1.2.4

### Environment that reproduces the issue

Devices [iOS & Android]

### Use case description

Is there any option to Capture Frames? I mean  to set up a mechanism to capture frames from the camera in real-time, like can do with react-native-camera, For some loading time to take capture frame and make it blur...

**Comment by ThibaultBee** [comment]
I still don't get it.
Could you describe in several steps? Or add a drawing, a video example or something like this?

**Comment by razamsalem** [comment]
I will explain it simply,
While the user is on the camera componnent and he wants to turn the phone to landscape, then while the camera adjusts itself to landscape, I want to capture a frame for one second and then to show it in blur  while the user waits for the camera to turn properly, for a better user experience.

**Comment by razamsalem** [comment]
> I still don't get it. Could you describe in several steps? Or add a drawing, a video example or something like this?


I will explain it simply,
While the user is on the camera componnent and he wants to turn the phone to landscape, then while the camera adjusts itself to landscape, I want to capture a frame for one second and then to show it in blur while the user waits for the camera to turn properly, for a better user experience.

**Comment by ThibaultBee** [comment]
Ok, now I see what you are trying to achieve.
It is not as easy as it seems.

We already have a lot to do, we are not going to invest time on this feature right now.
