### ISSUE TITLE
Not able to capture stream from Android 

### ISSUE THREAD

**Issue by LauraBeatris** [apivideo/api.video-reactnative-live-stream#8]
Hey! 👋🏻😁
Thanks for the library, we've been looking for a maintainable streaming library for a while and here's it 🎉

However, we're experiencing a weird issue, possibly from a configuration from our side, but we wanted to check with you first. The capture process is working on IOS but **not on Android**.

Here's our configuration:
```js
const liveStreamVideoOptions = {
  fps: 30,
  resolution: '720p',
  camera: 'front',
  orientation: 'portrait',
};
```
```jsx
 /// {...}
  const [streaming, setStreaming] = useState(false);
  const ref = useRef<ReactNativeLivestreamMethods>(null);

  const handlePress = () => {
    if (streaming) {
      ref.current?.stopStreaming();
      setStreaming(false);
    } else {
      ref.current?.startStreaming();
      setStreaming(true);
    }
  };

  return <LivestreamView
        style={stylesheet.livestreamView}
        ref={ref}
        video={liveStreamVideoOptions}
        liveStreamKey={streamKey}
        rtmpServerUrl={rtmpUrl}
      />
```

According to the docs, there's some setup needed for [permissions](https://github.com/apivideo/react-native-livestream#permissions), which is already implemented on our side 
```xml
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.CAMERA" />
```
And the permissions are also requested using `react-native-permissions` library. 
So finally, I wonder why we're not able to capture from Android devices, are we missing something?

**Comment by ThibaultBee** [comment]
Hi Laura,
I am not sure what is your issue. Do you have a camera preview? Did you try to call `startStreaming`?
Do you have any relevant traces in the logcat?

**Comment by szokodiakos** [comment]
Hey! Let me chime in as well (I'm working on this with Laura).

First of all thanks for the super quick response, I'll try to answer what we already know:

We do have camera preview, so the camera permission should be there. We did try to call startStreaming, we console.log'd the ref.current and it was also properly there so the function call is happened.

We do not have logcat logs at this time, we'll try to post it shortly but wanted to answer to these initial questions.

**Comment by naudej** [comment]
Hi there, is is the logcat from the session when we started the livestreaming. On metro there are no clear error logs getting shown maybe the logcat logs will shed more light as to the issue: https://pastebin.com/XwHfJYKq

**Comment by ThibaultBee** [comment]
`2021-11-18 10:22:46.257 21506-2328/app.foobar E/connection rtmp: error`
It seems that a connection failed event is triggered.
Are you sure of your rtmp URL and stream key?

Anyway, I think it might interest you: we current have https://github.com/apivideo/react-native-livestream/pull/7 where you can received events from RTMP stream in your UI.

**Comment by LauraBeatris** [comment]
RTPM URL and stream key are correct! 

One quick question: Why the stream key is being changed according to the platform, on the [example app from the repo]?(https://github.com/apivideo/api.video-reactnative-live-stream/blob/de9dd2f3dae437d2410cfbb9395d8081a6fc36ad/example/src/App.tsx#L37-L40)

And looking forward for the changes from https://github.com/apivideo/api.video-reactnative-live-stream/pull/7, may I ask when you are planning of releasing?

**Comment by LauraBeatris** [comment]
Hey @ThibaultBee - the issue was related to the format of the RTMP URL

For a reason that I'm not aware of yet, on Android, we need to pass an `/` on the end of the endpoint, otherwise, the connection fails

**Comment by LauraBeatris** [comment]
Appears to be due to how the native library concatenates with the stream key with the RTMP URL 

[rtmpCamera2.startStream(url + streamKey)](https://github.com/apivideo/api.video-android-live-stream/blob/432e44fb5cec619318fb03312f4b768b5130ea66/livestream/src/main/java/video/api/livestream/ApiVideoLiveStream.kt#L273)

**Comment by ThibaultBee** [comment]
Nice!
> For a reason that I'm not aware of yet, on Android, we need to pass an `/` on the end of the endpoint, otherwise, the connection fails

Our Android live stream library should add a `/` at the end of the url when it is missing. We will fix that later.

> One quick question: On the example app from the repo, why the stream key is being changed according to the platform?

It was only for test purpose, it should not have been commited.

> And looking forward to the changes from #7, may I ask when you are planning of releasing?

As there is a workaround to your issue, I guess we are ready for a delivery.

**Comment by LauraBeatris** [comment]
@ThibaultBee Thanks for the help so far!

**Comment by LauraBeatris** [comment]
@ThibaultBee Is [api.video-android-live-stream](https://github.com/apivideo/api.video-android-live-stream) the right repo? I could raise a PR there to handle this case

**Comment by ThibaultBee** [comment]
Yes, it is the right repo. But not the right branch. The master branch contains a huge refactoring that has not been ported to react native yet (see https://github.com/apivideo/api.video-reactnative-live-stream/tree/feature/update_livestream) because we also have to refactor the iOS live stream.

You can raise an issue there just to follow the fix, we will definitely implement this, just not now. As a short term workaround, if you could write a function that add `/` at the end of the RTMP URL when it is missing that will be great :)
