### ISSUE TITLE
[Bug]: package types point to non existent file.

### ISSUE THREAD

**Issue by BlueBazze** [apivideo/api.video-reactnative-live-stream#89]
### Version

v2.0.0

### Which operating systems have you used?

- [ ] Android
- [ ] iOS

### Environment that reproduces the issue

Noticed that the types in package.json is pointing to a type declaration that does not exist.
```
"types": "lib/typescript/index.d.ts",
```
https://github.com/apivideo/api.video-reactnative-live-stream/blob/main/package.json#L7
![image](https://github.com/user-attachments/assets/7eb716b9-d04b-4645-823c-781dff7ce3e1)

### Is it reproducible in the example application?

Yes

### RTMP Server

localhost

### Reproduction steps

Install @api.video/react-native-livestream in any project.
Try importing anything into a typescript file.

### Expected result

The imports from @api.video/react-native-livestream is typed.

### Actual result

The imports from @api.video/react-native-livestream is not typed.

**Comment by ThibaultBee** [comment]
See https://github.com/apivideo/api.video-reactnative-live-stream/pull/77/files

**Comment by BlueBazze** [comment]
Thanks, Sorry.
