### ISSUE TITLE
[Bug]: can't run android app

### ISSUE THREAD

**Issue by talhatsk** [apivideo/api.video-reactnative-live-stream#92]
### Version

v2.0.1

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

Oneplus 8T android 13

### Is it reproducible in the example application?

Not tested

### RTMP Server

*

### Reproduction steps

Update the package and yarn android

### Expected result

App should be installed 

### Actual result

app building is failing with this error
Execution failed for task ':app:mergeExtDexDevelopmentDebug'.
`Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.`
`Failed to transform camera-viewfinder-1.4.0-alpha06.aar (androidx.camera:camera-viewfinder:1.4.0-alpha06) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.`
`Execution failed for DexingWithClasspathTransform: /Users/talhashafique/.gradle/caches/transforms-3/a2f592b30fddcb727f0b2169f047a323/transformed/jetified-camera-viewfinder-1.4.0-alpha06-runtime.jar.`
`Error while dexing.`

### Relevant logs output

```shell
Execution failed for task ':app:mergeExtDexDevelopmentDebug'.
> Could not resolve all files for configuration ':app:developmentDebugRuntimeClasspath'.
   > Failed to transform camera-viewfinder-1.4.0-alpha06.aar (androidx.camera:camera-viewfinder:1.4.0-alpha06) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/talhashafique/.gradle/caches/transforms-3/a2f592b30fddcb727f0b2169f047a323/transformed/jetified-camera-viewfinder-1.4.0-alpha06-runtime.jar.
         > Error while dexing.
```

**Comment by ThibaultBee** [comment]
Have you tried to look for this issue on google and stackoverflow?
As CI is properly running for Android, it does not seem to comme directly from this package.

**Comment by MAzeem6778** [comment]
I'm encountering the same issue after upgrading to version 2.0.1. The Android app runs successfully when I revert back to version 2.0.0.

**Comment by talhatsk** [comment]
> ```shell
> Execution failed for task ':app:mergeExtDexDevelopmentDebug'.
> ```

yes @ThibaultBee i have tried looking over these forums but can't find anything about this issue. I think the issue might be that new version is conflicting with the project build gradle version.

**Comment by talhatsk** [comment]
> > ```shell
> > Execution failed for task ':app:mergeExtDexDevelopmentDebug'.
> > ```
> 
> yes @ThibaultBee i have tried looking over these forums but can't find anything about this issue. I think the issue might be that new version is conflicting with the project build gradle version.



> Have you tried to look for this issue on google and stackoverflow? As CI is properly running for Android, it does not seem to comme directly from this package.
yes @ThibaultBee i have tried looking over these forums but can't find anything about this issue. I think the issue might be that new version is conflicting with the project build gradle version.

**Comment by ThibaultBee** [comment]
From what I undertand, you did find a way out of this issue. How did you manage to fix it?

**Comment by talhatsk** [comment]
> From what I undertand, you did find a way out of this issue. How did you manage to fix it?

for me it worked by upgrading the build gradle version

**Comment by ThibaultBee** [comment]
So what is your new AGP version?

**Comment by talhatsk** [comment]
> So what is your new AGP version?

8.6

**Comment by ThibaultBee** [comment]
Ok thanks.
I am closing this issue as it is resolved.
